import "./scripts/themer"
import "./scripts/precedents"
import "./scripts/patches"
import "./scripts/disable-signatures"
import "./scripts/paginator"
import "./scripts/settings"
import "./scripts/threads"
